[tool.bumpversion]
current_version = "0.2.0"
commit = true
message = "chore: bump version to {new_version}"
tag = true
tag_name = "v{new_version}"
tag_message = "Version {new_version}"

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "## Unreleased"
replace = """
## Unreleased

## v{new_version} - {now:%Y-%m-%d}"""
